#!/usr/bin/env python3
"""MNEMOS Onboarding — bootstrap MNEMOS integration in a consumer application.

Generates boundary adapter stub, env template, health smoke test,
and an integration quick-start doc in the consumer app's workspace.

Usage:
  python tools/mnemos_onboard.py --target /path/to/consumer-app
  python tools/mnemos_onboard.py --target /path/to/consumer-app --workspace mnemos_integration
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


_BOUNDARY_TEMPLATE = '''\
"""
MNEMOS Boundary Adapter — auto-generated by mnemos_onboard.py
================================================================

Pre-wired boundary for calling the MNEMOS memory service.
Customize the methods below for your application's use case.
"""

from mnemos_sdk import MnemosClient, MnemosConfig


class MnemosBoundary:
    """Application boundary for the MNEMOS memory service."""

    def __init__(self, prefix: str = "MNEMOS"):
        self._config = MnemosConfig.from_env(prefix)
        self._client = MnemosClient(self._config)

    def ensure_ready(self) -> bool:
        """Wait for MNEMOS to become available. Call at app startup."""
        return self._client.wait_until_ready()

    @property
    def healthy(self) -> bool:
        resp = self._client.health()
        return resp.ok

    def store(self, content: str, *, source: str = "", tags: list[str] | None = None,
              metadata: dict | None = None):
        """Store a single document as an engram."""
        doc = {
            "content": content,
            "source": source,
            "neuro_tags": tags or [],
            "metadata": metadata or {},
        }
        resp = self._client.index([doc])
        if not resp.ok:
            raise RuntimeError(f"MNEMOS index failed: {resp.error}")
        return resp.data.get("result", {})

    def recall(self, query: str, *, top_k: int = 5):
        """Search MNEMOS and return ranked hits."""
        hits = self._client.search(query, top_k=top_k)
        return [
            {"content": h.engram.get("content", ""), "score": h.score, "tier": h.tier}
            for h in hits
        ]

    def forget(self, engram_id: str):
        """Delete an engram from all tiers."""
        resp = self._client.delete_engram(engram_id)
        if not resp.ok:
            raise RuntimeError(f"MNEMOS delete failed: {resp.error}")
        return resp.data.get("result", {})
'''

_ENV_TEMPLATE = """\
# ─── MNEMOS Connection ────────────────────────────────
# Set these in your .env or docker-compose environment

MNEMOS_BASE_URL=http://localhost:8700
MNEMOS_TOKEN=
MNEMOS_TIMEOUT_S=5
MNEMOS_READY_WAIT_S=10
MNEMOS_RETRIES=2
MNEMOS_RETRY_DELAY_S=0.5
MNEMOS_ENABLED=true
"""

_SMOKE_TEST_TEMPLATE = """\
{
  "service": "mnemos-service",
  "base_url_env": "MNEMOS_BASE_URL",
  "default_base_url": "http://localhost:8700",
  "checks": [
    {
      "name": "health",
      "method": "GET",
      "path": "/health",
      "expect_status": 200,
      "expect_json_fields": ["status"]
    },
    {
      "name": "capabilities",
      "method": "GET",
      "path": "/v1/mnemos/capabilities",
      "expect_status": 200,
      "expect_json_fields": ["contract_version", "status", "feature", "supports"]
    }
  ]
}
"""


_QUICKSTART_TEMPLATE = """\
# MNEMOS Integration — Quick Start

> Auto-generated by `mnemos_onboard.py` on {timestamp}

## 1. Start MNEMOS

```bash
# Option A: Docker Compose (recommended)
cd /path/to/MNEMOS
docker compose up -d --build

# Option B: Local dev
pip install -r requirements.txt
python -m service.app
```

## 2. Configure Connection

Copy `.env.mnemos` values into your app's environment or `.env` file.

Key variables:
- `MNEMOS_BASE_URL` — default `http://localhost:8700`
- `MNEMOS_TOKEN` — leave empty for local dev

## 3. Install SDK

```bash
pip install -e /path/to/MNEMOS   # or add mnemos_sdk to your requirements
```

## 4. Use the Boundary Adapter

```python
from mnemos_boundary import MnemosBoundary

memory = MnemosBoundary()
memory.ensure_ready()

# Store
memory.store("Important fact about quantum computing", source="research",
             tags=["physics", "quantum"])

# Recall
results = memory.recall("quantum computing advances", top_k=3)
for r in results:
    print(f"  [{{r['score']:.3f}}] {{r['content'][:80]}}")
```

## 5. Validate Integration

```bash
python -c "from mnemos_sdk import MnemosClient, MnemosConfig; c = MnemosClient(MnemosConfig.from_env()); print('ready' if c.wait_until_ready() else 'not ready')"
```

## 6. Run Health Audit (optional)

```bash
python /path/to/MNEMOS/tools/mnemos_health_audit.py
```
"""


def _write(path: Path, content: str, *, force: bool = False) -> bool:
    if path.exists() and not force:
        print(f"  [SKIP] {path} (exists, use --force to overwrite)")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  [CREATED] {path}")
    return True


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Bootstrap MNEMOS integration in a consumer app")
    parser.add_argument("--target", required=True, help="Path to consumer application root")
    parser.add_argument("--workspace", default="mnemos_integration", help="Output folder name (default: mnemos_integration)")
    parser.add_argument("--force", action="store_true", help="Overwrite existing generated files")
    args = parser.parse_args(argv)

    target = Path(args.target).resolve()
    if not target.exists():
        print(f"[ERROR] Target path does not exist: {target}")
        return 1

    workspace = target / args.workspace
    workspace.mkdir(parents=True, exist_ok=True)

    print(f"\n== MNEMOS Onboarding ==")
    print(f"Target: {target}")
    print(f"Workspace: {workspace}\n")

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    _write(workspace / "mnemos_boundary.py", _BOUNDARY_TEMPLATE, force=args.force)
    _write(workspace / ".env.mnemos", _ENV_TEMPLATE, force=args.force)
    _write(workspace / "mnemos_smoke_spec.json", _SMOKE_TEST_TEMPLATE, force=args.force)
    _write(workspace / "MNEMOS_QUICKSTART.md",
           _QUICKSTART_TEMPLATE.format(timestamp=timestamp), force=args.force)

    # Context manifest for AI dev tools
    manifest = {
        "generator": "mnemos_onboard.py",
        "generated_at": timestamp,
        "target": str(target),
        "workspace": str(workspace),
        "artifacts": {
            "boundary": "mnemos_boundary.py",
            "env_template": ".env.mnemos",
            "smoke_spec": "mnemos_smoke_spec.json",
            "quickstart": "MNEMOS_QUICKSTART.md",
        },
    }
    _write(workspace / "context_manifest.json",
           json.dumps(manifest, indent=2), force=args.force)

    print(f"\n✅ Onboarding complete. See {workspace / 'MNEMOS_QUICKSTART.md'} to get started.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
