"""
MNEMOS Installer — Config Renderer
=====================================

Generates docker-compose.generated.yml, .env.mnemos,
and mnemos_profile.yaml from the selected profile.
"""

import datetime
import json
import os
import shutil
from pathlib import Path
from typing import Optional

from installer.profiles import ProfileSpec
from installer.questions import UserAnswers
from installer.probes import ProbeResults
from installer.recommend import Recommendation


TEMPLATES_DIR = Path(__file__).parent / "templates"


def render_compose(profile: ProfileSpec, output_dir: Path = Path(".")) -> Path:
    """Copy the profile-specific compose template to output directory."""
    template_file = TEMPLATES_DIR / f"{profile.name}.yml"
    output_file = output_dir / "docker-compose.generated.yml"

    if template_file.exists():
        shutil.copy2(template_file, output_file)
    else:
        # For custom_manual, create a minimal compose
        output_file.write_text(
            "# MNEMOS — Custom Manual Profile\n"
            "# No compose template for this profile.\n"
            "# Provide your own docker-compose.yml configuration.\n"
        )

    return output_file


def render_env(
    profile: ProfileSpec,
    output_dir: Path = Path("."),
    retrieval_mode: str = "semantic",
    fusion_policy: str = "balanced",
    lexical_top_k: int = 25,
    semantic_top_k: int = 25,
    explain_default: bool = False,
) -> Path:
    """Generate .env.mnemos from profile spec."""
    output_file = output_dir / ".env.mnemos"

    lines = [
        "# MNEMOS Environment Configuration",
        f"# Generated by MNEMOS Installer — {datetime.datetime.now().isoformat()}",
        f"# Profile: {profile.display_name}",
        "",
    ]

    # Profile env vars
    for key, value in profile.env_vars.items():
        lines.append(f"{key}={value}")

    # Standard vars
    defaults = {
        "MNEMOS_GPU_DEVICE": "cuda",
        "MNEMOS_QUANT_BITS": "4",
        "MNEMOS_EMBEDDING_MODEL": "all-MiniLM-L6-v2",
        "MNEMOS_PORT": "8700",
        "MNEMOS_TOKEN": "",
        "MNEMOS_AUDIT_ENABLED": "true",
        "MNEMOS_LOG_LEVEL": "INFO",
        "MNEMOS_RETRIEVAL_MODE": retrieval_mode,
        "MNEMOS_FUSION_POLICY": fusion_policy,
        "MNEMOS_LEXICAL_TOP_K": str(lexical_top_k),
        "MNEMOS_SEMANTIC_TOP_K": str(semantic_top_k),
        "MNEMOS_EXPLAIN_DEFAULT": "true" if explain_default else "false",
    }

    # Profile-specific defaults
    if profile.name == "core_memory_appliance":
        defaults["MNEMOS_QDRANT_URL"] = "http://qdrant:6333"
        defaults["MNEMOS_QDRANT_COLLECTION"] = "mnemos_engrams"
        defaults["MNEMOS_POSTGRES_DSN"] = "postgresql://mnemos:mnemos@postgres:5432/mnemos"
    elif profile.name == "governance_native":
        defaults["MNEMOS_POSTGRES_DSN"] = "postgresql://mnemos:mnemos@postgres:5432/mnemos"
        defaults["MNEMOS_PGVECTOR_TABLE"] = "mnemos_vectors"

    lines.append("")
    for key, value in defaults.items():
        if key not in profile.env_vars:
            lines.append(f"{key}={value}")

    output_file.write_text("\n".join(lines) + "\n")
    return output_file


def render_manifest(
    recommendation: Recommendation,
    answers: UserAnswers,
    probes: ProbeResults,
    output_dir: Path = Path("."),
    retrieval_mode: str = "semantic",
    fusion_policy: str = "balanced",
    lexical_top_k: int = 25,
    semantic_top_k: int = 25,
    explain_default: bool = False,
) -> Path:
    """Generate mnemos_profile.yaml source-of-truth manifest."""
    output_file = output_dir / "mnemos_profile.yaml"

    manifest = {
        "mnemos_profile": {
            "version": "1.0",
            "generated_at": datetime.datetime.now().isoformat(),
            "install_type": "new",
            "profile": {
                "name": recommendation.profile.name,
                "display_name": recommendation.profile.display_name,
                "confidence": recommendation.confidence,
                "reasons": recommendation.reasons,
                "warnings": recommendation.warnings,
                "alternatives": recommendation.alternatives,
            },
            "user_answers": {
                "use_case": answers.use_case,
                "priority": answers.priority,
                "scale": answers.scale,
                "strict_filters": answers.strict_filters,
                "prefer_manual": answers.prefer_manual,
            },
            "host_facts": {
                "gpu_available": probes.gpu_available,
                "gpu_name": probes.gpu_name,
                "vram_mb": probes.vram_mb,
                "ram_gb": probes.ram_gb,
                "disk_free_gb": probes.disk_free_gb,
                "docker_available": probes.docker_available,
                "nvidia_runtime": probes.nvidia_runtime,
                "existing_postgres": probes.existing_postgres,
                "os": probes.os_name,
                "cpu_cores": probes.cpu_cores,
            },
            "enabled_services": recommendation.profile.services,
            "retrieval": {
                "mode": retrieval_mode,
                "fusion_policy": fusion_policy,
                "lexical_top_k": lexical_top_k,
                "semantic_top_k": semantic_top_k,
                "explain_default": explain_default,
            },
            "generated_files": [
                "docker-compose.generated.yml",
                ".env.mnemos",
                "mnemos_profile.yaml",
            ],
        }
    }

    # Write as YAML-like format (avoid pyyaml dependency)
    lines = _dict_to_yaml(manifest)
    output_file.write_text("\n".join(lines) + "\n")
    return output_file


def _dict_to_yaml(data: dict, indent: int = 0) -> list:
    """Simple dict-to-YAML renderer (avoids pyyaml dependency)."""
    lines = []
    prefix = "  " * indent
    for key, value in data.items():
        if isinstance(value, dict):
            lines.append(f"{prefix}{key}:")
            lines.extend(_dict_to_yaml(value, indent + 1))
        elif isinstance(value, list):
            lines.append(f"{prefix}{key}:")
            for item in value:
                if isinstance(item, dict):
                    lines.append(f"{prefix}  -")
                    lines.extend(_dict_to_yaml(item, indent + 2))
                else:
                    lines.append(f"{prefix}  - {item}")
        elif isinstance(value, bool):
            lines.append(f"{prefix}{key}: {'true' if value else 'false'}")
        elif value is None:
            lines.append(f"{prefix}{key}: null")
        else:
            lines.append(f"{prefix}{key}: {value}")
    return lines
